### ISSUE TITLE
Code is not is the correct column when viewing jquery

### ISSUE THREAD

**Issue by humbertoroa** [bendytree/explainjs#1]
I was viewing the jquery source using explainjs.com, and the code moved the wrong column at about 60% down the page. I am attaching a screen capture that shows the code segment where the issue starts. 

Screen capture: ![issue](https://f.cloud.github.com/assets/1650890/459917/f472d576-b40e-11e2-9699-a756f8711d19.png)

**Comment by bendytree** [comment]
Thanks for the heads up, I'll look into it

**Comment by bendytree** [comment]
Looks like it wasn't properly handling HTML in comments. I wrote a test to reproduce the issue & patched it. 02d035087dc3d78ee97b79a31d62793a6bfbab63 Thanks again for the heads up.
